-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- Table to store valid anomaly references (the "Brain" of the AI)
create table anomaly_references (
    id uuid primary key default gen_random_uuid(),
    name text not null,                -- e.g., 'Engine Knock', 'Belt Squeal'
    description text,
    embedding vector(384),             -- Representative vector for this sound (384 dim is common for audio models)
    confidence_threshold float default 0.7, -- Minimum similarity to trigger a match
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table to log analysis results (History)
create table analysis_logs (
    id uuid primary key default gen_random_uuid(),
    status text not null,              -- 'healthy', 'anomaly_detected'
    detected_anomaly_name text,        -- Name of the match if any
    confidence_score float,
    audio_chunk_ref text,              -- Optional link to stored audio blob
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert some dummy reference data (MOCK EMBEDDINGS)
-- In a real scenario, these would be generated by a Python script running 'librosa' or a Transformer model
insert into anomaly_references (name, description, confidence_threshold)
values 
    ('Engine Knocking', 'Sharp metallic tapping sounds indicating piston issues', 0.8),
    ('Belt Squeal', 'High pitched screeching indicatnig loose tensioner', 0.75),
    ('Exhaust Leak', 'Loud ticking or sputtering noise from exhaust manifold', 0.7);
