/**
 * audioDatasetService.js — Vroomie Reference Library v6 (WAV-direct)
 *
 * ARCHITECTURE (v6 — WAV-direct with guaranteed preprocessing parity):
 *
 *   Priority 1: Download JSON fingerprints from Supabase bucket.
 *               These MUST be in v6-log10-exact pipeline format (generated by regen_fingerprints.cjs).
 *               Validation: cosine_vec values must be <= 0 (log10 space).
 *
 *   Priority 2: Download WAV files directly and process them in the browser
 *               using AudioContext.decodeAudioData() + the SAME FFT algorithm
 *               as AudioV6_Calibrator.worker.js. This guarantees preprocessing parity.
 *               Results are cached in IndexedDB so processing happens only once.
 *
 *   Priority 3: Acoustically-grounded built-in profiles (last resort).
 *
 * The root cause of all previous failures:
 *   Old JSON fingerprints used v5-symmetric [0,1] normalized values.
 *   V6 worker produces log10(cleanMag) which is always NEGATIVE (typically -8 to -1).
 *   Cosine similarity between all-positive reference and all-negative live vector = ~0.
 *   No threshold could ever be met → "No anomalies detected" always.
 */

import { supabase } from '../lib/supabase';
import { Logger } from '../lib/logger';
import { DTW_FINGERPRINTS } from '../data/dtwFingerprints_v3';

export let referenceIndex = [];

// Feature flags
export const audio_matching_v4_final           = true;
export const audio_matching_final_v5_hardened  = true;
export const audio_matching_mechanical_v2      = true;
export const audio_v6_calibration             = true;

// ── V6 worker FFT constants (MUST match AudioV6_Calibrator.worker.js) ─────────
const TARGET_SR  = 44100;
const FFT_SIZE   = 4096;
const HOP        = FFT_SIZE >> 1;
const BIN_4KHZ   = Math.round(4000  * FFT_SIZE / TARGET_SR); // 371
const BIN_12KHZ  = Math.round(12000 * FFT_SIZE / TARGET_SR); // 1114
const VECTOR_LEN = BIN_12KHZ - BIN_4KHZ;                     // 743
const SS_ALPHA   = 1.5;
const SS_BETA    = 0.01;

// ── IndexedDB cache for in-browser processed WAV fingerprints ─────────────────
const IDB_DB      = 'vroomie-fingerprints-v6';
const IDB_STORE   = 'fingerprints';
const IDB_VERSION = 1;

function openIDB() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(IDB_DB, IDB_VERSION);
    req.onupgradeneeded = e => e.target.result.createObjectStore(IDB_STORE, { keyPath: 'id' });
    req.onsuccess  = e => resolve(e.target.result);
    req.onerror    = e => reject(e.target.error);
  });
}

async function idbGet(db, key) {
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(IDB_STORE, 'readonly');
    const req = tx.objectStore(IDB_STORE).get(key);
    req.onsuccess = e => resolve(e.target.result);
    req.onerror   = e => reject(e.target.error);
  });
}

async function idbPut(db, record) {
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(IDB_STORE, 'readwrite');
    const req = tx.objectStore(IDB_STORE).put(record);
    req.onsuccess = e => resolve(e.target.result);
    req.onerror   = e => reject(e.target.error);
  });
}

// ── Validate embedding length ────
function isValidEmbedding(vec) {
  return Array.isArray(vec) && vec.length >= 100;
}

// ── Pearson correlation for deduplication ────────────────────────────────────
function pearsonCorr(a, b) {
  const len = Math.min(a.length, b.length);
  if (len === 0) return 0;
  let sumA = 0, sumB = 0;
  for (let i = 0; i < len; i++) { sumA += a[i]; sumB += b[i]; }
  const mA = sumA / len, mB = sumB / len;
  let dot = 0, nA = 0, nB = 0;
  for (let i = 0; i < len; i++) {
    const ca = a[i] - mA, cb = b[i] - mB;
    dot += ca * cb; nA += ca * ca; nB += cb * cb;
  }
  return (nA < 1e-12 || nB < 1e-12) ? 0 : dot / (Math.sqrt(nA) * Math.sqrt(nB));
}

// ── Hanning window ─────────────────────────────────────────────────────────────
function applyHanning(signal, N) {
  const out = new Float32Array(N);
  for (let i = 0; i < N; i++)
    out[i] = signal[i] * (0.5 * (1 - Math.cos((2 * Math.PI * i) / (N - 1))));
  return out;
}

// ── Cooley-Tukey FFT (identical to V6 worker) ─────────────────────────────────
function computeFFT(signal, N) {
  const re = new Float32Array(N);
  const im = new Float32Array(N);
  const copyLen = Math.min(signal.length, N);
  for (let i = 0; i < copyLen; i++) re[i] = signal[i];
  let j = 0;
  for (let i = 1; i < N; i++) {
    let bit = N >> 1;
    for (; j & bit; bit >>= 1) j ^= bit;
    j ^= bit;
    if (i < j) {
      [re[i], re[j]] = [re[j], re[i]];
      [im[i], im[j]] = [im[j], im[i]];
    }
  }
  for (let len = 2; len <= N; len <<= 1) {
    const ang = -2 * Math.PI / len;
    const wRe = Math.cos(ang), wIm = Math.sin(ang);
    for (let i = 0; i < N; i += len) {
      let cRe = 1, cIm = 0;
      for (let k = 0; k < len / 2; k++) {
        const uRe = re[i+k], uIm = im[i+k];
        const vRe = re[i+k+len/2]*cRe - im[i+k+len/2]*cIm;
        const vIm = re[i+k+len/2]*cIm + im[i+k+len/2]*cRe;
        re[i+k] = uRe+vRe; im[i+k] = uIm+vIm;
        re[i+k+len/2] = uRe-vRe; im[i+k+len/2] = uIm-vIm;
        const nRe = cRe*wRe - cIm*wIm;
        cIm = cRe*wIm + cIm*wRe;
        cRe = nRe;
      }
    }
  }
  return { re, im };
}

// ── Generate V6 cosine_vec from decoded Float32Array (browser, same as worker) ─
function generateV6CosineVec(samples) {
  // samples is already resampled to TARGET_SR by AudioContext, already mono
  // Step 1: Peak normalize
  let maxVal = 0;
  for (let i = 0; i < samples.length; i++) {
    const a = Math.abs(samples[i]);
    if (a > maxVal) maxVal = a;
  }
  const normalized = maxVal < 1e-8 ? samples : samples.map(v => v / maxVal);

  // Step 2: Build noise profile from first 100ms (same as V6 buildNoiseProfile)
  const NOISE_LEN = Math.round(TARGET_SR * 0.1);
  const noiseMag  = new Float32Array(FFT_SIZE >> 1);
  let noiseFrames = 0;
  for (let off = 0; off + FFT_SIZE <= NOISE_LEN && off + FFT_SIZE <= normalized.length; off += HOP) {
    const frame = applyHanning(normalized.slice(off, off + FFT_SIZE), FFT_SIZE);
    const { re, im } = computeFFT(frame, FFT_SIZE);
    for (let i = 0; i < FFT_SIZE >> 1; i++)
      noiseMag[i] += Math.sqrt(re[i]*re[i] + im[i]*im[i]);
    noiseFrames++;
  }
  if (noiseFrames > 0)
    for (let i = 0; i < FFT_SIZE >> 1; i++) noiseMag[i] /= noiseFrames;

  // Step 3: Process frames — generate log10(cleanMag) same as V6 processFrame()
  const accum = new Float64Array(VECTOR_LEN);
  let frameCount = 0;

  for (let off = 0; off + FFT_SIZE <= normalized.length; off += HOP) {
    const slice = normalized.slice(off, off + FFT_SIZE);
    const maxS  = slice.reduce((m, v) => Math.max(m, Math.abs(v)), 0);
    if (maxS > 0.98) continue; // skip clipped (same as worker)

    const windowed = applyHanning(slice, FFT_SIZE);
    const { re, im } = computeFFT(windowed, FFT_SIZE);

    for (let i = BIN_4KHZ; i < BIN_12KHZ; i++) {
      const rawMag   = Math.sqrt(re[i]*re[i] + im[i]*im[i]);
      const rawPow   = rawMag * rawMag;
      const nPow     = noiseMag[i] * noiseMag[i];
      const cleanPow = Math.max(rawPow - SS_ALPHA * nPow, SS_BETA * rawPow);
      const cleanMag = Math.sqrt(cleanPow);
      accum[i - BIN_4KHZ] += Math.log10(Math.max(Number.EPSILON, cleanMag));
    }
    frameCount++;
  }

  if (frameCount < 2) return null;
  return Array.from(accum).map(v => v / frameCount);
}

// ── Derive label/fault_type/severity from filename ────────────────────────────
function deriveMetadata(baseName) {
  const b = baseName.toLowerCase();
  let fault_type = baseName;
  let severity   = 'high';

  if (b.includes('critical')) severity = 'critical';
  else if (b.includes('medium') || b.includes('moderate')) severity = 'medium';
  else if (b.includes('low'))  severity = 'low';

  if (b.includes('alternator') || (b.includes('bearing') && !b.includes('water')))
    fault_type = 'alternator_bearing_fault';
  else if (b.includes('intake') || b.includes('leak'))
    fault_type = 'intake_leak';
  else if (b.includes('water_pump') || b.includes('waterpump'))
    fault_type = 'water_pump';
  else if (b.includes('motor') || b.includes('starter'))
    fault_type = 'motor_starter';
  else if (b.includes('piston') || b.includes('knock'))
    fault_type = 'piston_knock';
  else if (b.includes('serpentine') || (b.includes('belt') && !b.includes('power')))
    fault_type = 'serpentine_belt';
  else if (b.includes('power_steering') || b.includes('powersteeringpump') || b.includes('powersteer'))
    fault_type = 'power_steering';
  else if (b.includes('timing') || b.includes('chain'))
    fault_type = 'timing_chain';
  else if (b.includes('rocker') || b.includes('valve'))
    fault_type = 'rocker_valve';
  else if (b.includes('low_oil') || b.includes('oil'))
    fault_type = 'low_oil';

  return { label: baseName, fault_type, severity };
}

// ── Main init function ────────────────────────────────────────────────────────
export async function initializeAudioDataset(forceRefresh = false) {
  if (!forceRefresh && referenceIndex && referenceIndex.length > 0) {
    Logger.info(`[Dataset] Already loaded ${referenceIndex.length} refs — skipping re-init`);
    return;
  }

  referenceIndex = [];
  Logger.info('🎵 [Dataset V8] Initializing DTW sequence reference library...');

  if (DTW_FINGERPRINTS && DTW_FINGERPRINTS.length > 0) {
    for (const fp of DTW_FINGERPRINTS) {
      if (!fp.dtw_sequence || fp.dtw_sequence.length < 10) continue;
      referenceIndex.push(fp);
    }

    const byType = {};
    referenceIndex.forEach(r => { byType[r.fault_type] = (byType[r.fault_type]||0)+1; });
    Logger.info(`[Dataset] ✅ Loaded ${referenceIndex.length} DTW sequences:`, JSON.stringify(byType));
    return;
  }



  // ── Fallback: Supabase bucket ─────────────────────────────────────────────────
  Logger.info('[Dataset] No embedded fingerprints found. Falling back to Supabase bucket...');

  try {
    // ── 1. List bucket files ──────────────────────────────────────────────────
    const { data: files, error: listError } = await supabase.storage
      .from('anomaly-patterns')
      .list('', { limit: 500, sortBy: { column: 'name', order: 'asc' } });

    if (listError) {
      Logger.warn('[Dataset] Bucket list failed:', listError.message);
    } else if (files && files.length > 0) {
      const jsonFiles = files.filter(f => f.name.endsWith('.json'));
      const wavFiles  = files.filter(f => f.name.toLowerCase().endsWith('.wav'));

      Logger.info(`[Dataset] Bucket: ${jsonFiles.length} JSON, ${wavFiles.length} WAV`);

      // ── 2. Load JSON fingerprints (v6-log10-exact format ONLY) ───────────
      let v6JsonCount  = 0;
      let rejectedOld  = 0;
      const processedWavNames = new Set();

      for (const file of jsonFiles) {
        const { data: blob, error: dlErr } = await supabase.storage
          .from('anomaly-patterns').download(file.name);

        if (dlErr || !blob) continue;

        let pattern;
        try {
          pattern = JSON.parse(await blob.text());
        } catch { continue; }

        if (!pattern || !pattern.label) continue;

        // ── CRITICAL: Reject old v5-symmetric fingerprints ────────────────
        // v5 uses [0,1] normalized values (all positive). V6 uses log10
        // (all negative). Cosine similarity between them = ~0 → no detection.
        if (Array.isArray(pattern.cosine_vec) && pattern.cosine_vec.length > 100) {
          if (!isValidEmbedding(pattern.cosine_vec)) {
            Logger.warn(`[Dataset] REJECTING ${file.name} — invalid vector. Run generate_v7_fingerprints.mjs to fix.`);
            rejectedOld++;
            continue;
          }

          const entry = {
            id:              pattern.id || file.name,
            label:           pattern.label,
            fault_type:      pattern.fault_type || null,
            severity:        pattern.severity || 'high',
            source_file:     pattern.source_file || file.name,
            cosine_vec:      pattern.cosine_vec,
            kurtosis_score:  pattern.kurtosis_score ?? 3,
            flatness_score:  pattern.flatness_score ?? 0.5,
            transient_score: pattern.transient_score ?? 0,
          };

          referenceIndex.push(entry);
          processedWavNames.add(pattern.source_file || '');
          v6JsonCount++;
        }
      }

      Logger.info(`[Dataset] Loaded ${v6JsonCount} v6 JSON refs, rejected ${rejectedOld} old v5 fingerprints`);

      // ── 3. For WAV files with no valid JSON, process them in-browser ──────
      // This guarantees parity even without running the regen script.
      let idb = null;
      try { idb = await openIDB(); } catch (e) { Logger.warn('[Dataset] IndexedDB unavailable:', e.message); }

      for (const wavFile of wavFiles) {
        const baseName = wavFile.name.replace(/\.wav$/i, '');
        if (processedWavNames.has(wavFile.name)) continue; // already have valid JSON

        // Check IndexedDB cache first
        if (idb) {
          const cached = await idbGet(idb, baseName).catch(() => null);
          if (cached && isValidEmbedding(cached.cosine_vec)) {
            referenceIndex.push(cached);
            Logger.info(`[Dataset] Loaded from IndexedDB cache: ${baseName}`);
            continue;
          }
        }

        Logger.info(`[Dataset] Processing WAV directly: ${wavFile.name}`);

        try {
          // Download WAV
          const { data: wavBlob, error: wavDlErr } = await supabase.storage
            .from('anomaly-patterns').download(wavFile.name);
          if (wavDlErr || !wavBlob) continue;

          // Decode using Web Audio API (handles all formats + resampling)
          const arrayBuf  = await wavBlob.arrayBuffer();
          const offlineCtx = new OfflineAudioContext(1, 1, TARGET_SR);
          let audioBuffer;
          try {
            audioBuffer = await offlineCtx.decodeAudioData(arrayBuf);
          } catch (decodeErr) {
            Logger.warn(`[Dataset] decodeAudioData failed for ${wavFile.name}: ${decodeErr.message}`);
            continue;
          }

          // Mix to mono (AudioContext already resampled to TARGET_SR)
          const numCh   = audioBuffer.numberOfChannels;
          const numSamp = audioBuffer.length;
          const mono    = new Float32Array(numSamp);
          for (let ch = 0; ch < numCh; ch++) {
            const chData = audioBuffer.getChannelData(ch);
            for (let i = 0; i < numSamp; i++) mono[i] += chData[i];
          }
          for (let i = 0; i < numSamp; i++) mono[i] /= numCh;

          // Generate V6 fingerprint
          const cosineVec = generateV6CosineVec(mono);
          if (!cosineVec) {
            Logger.warn(`[Dataset] WAV too short to fingerprint: ${wavFile.name}`);
            continue;
          }

          const { label, fault_type, severity } = deriveMetadata(baseName);
          const entry = {
            id:              baseName,
            label,
            fault_type,
            severity,
            source_file:     wavFile.name,
            cosine_vec:      cosineVec,
            kurtosis_score:  3,
            flatness_score:  0.5,
            transient_score: 0,
          };

          referenceIndex.push(entry);

          // Cache to IndexedDB for future sessions
          if (idb) {
            await idbPut(idb, entry).catch(() => {});
          }

          Logger.info(`[Dataset] ✅ WAV fingerprinted in-browser: ${baseName} (${cosineVec.length} dims)`);

        } catch (wavErr) {
          Logger.warn(`[Dataset] WAV processing error ${wavFile.name}:`, wavErr.message);
        }
      }
    }

    if (referenceIndex.length > 0) {
      // Group by fault type for summary log
      const byType = {};
      referenceIndex.forEach(r => { byType[r.fault_type] = (byType[r.fault_type] || 0) + 1; });
      console.log(`[Dataset] ✅ ${referenceIndex.length} references loaded:`, byType);
      return;
    }

    // ── 4. LAST RESORT: acoustically-grounded built-in profiles ──────────────
    Logger.warn('[Dataset] No valid v6 fingerprints found. Using built-in profiles as LAST RESORT.');
    Logger.warn('[Dataset] Run: node scripts/regen_fingerprints.cjs — to generate proper fingerprints.');
    loadBuiltinProfiles();

  } catch (err) {
    Logger.error('[Dataset] Fatal error:', err.message);
    if (referenceIndex.length === 0) loadBuiltinProfiles();
  }
}

// ── Built-in acoustically-grounded log10-space profiles (last resort) ─────────
// These are in V6 log10 space (negative values) — NOT the old v5 [0,1] space.
function loadBuiltinProfiles() {
  const VEC_LEN = VECTOR_LEN; // 743

  // Gaussian bell in log10 space
  const bell = (i, peakFrac, width, amp) =>
    amp * Math.exp(-0.5 * Math.pow((i / VEC_LEN - peakFrac) / width, 2));

  // Bearing: strong 4-6kHz band, harmonics, high kurtosis — log10 space baseline ~-3
  referenceIndex.push({
    id: 'builtin-bearing', label: 'alternator_bearing_fault_critical',
    fault_type: 'alternator_bearing_fault', severity: 'critical', source_file: 'builtin',
    cosine_vec: Array.from({ length: VEC_LEN }, (_, i) => {
      const f = i / VEC_LEN;
      return -3 + bell(i, 0.15, 0.07, 3) + bell(i, 0.30, 0.04, 2) - f * 1.5;
    }),
    kurtosis_score: 18, flatness_score: 0.05, transient_score: 0.1,
  });

  // Intake leak: broadband hiss, high flatness, flat HF — log10 space baseline ~-4
  referenceIndex.push({
    id: 'builtin-intake', label: 'intake_leak_low',
    fault_type: 'intake_leak', severity: 'medium', source_file: 'builtin',
    cosine_vec: Array.from({ length: VEC_LEN }, (_, i) => {
      const f = i / VEC_LEN;
      return -4.5 + (f > 0.5 ? 2.5 * f : 0.3 * f);
    }),
    kurtosis_score: 3.5, flatness_score: 0.78, transient_score: 0.05,
  });

  // Water pump: low-freq dominant, near-silent in 4kHz+ band — log10 baseline ~-6
  referenceIndex.push({
    id: 'builtin-wp', label: 'water_pump_failure_critical',
    fault_type: 'water_pump', severity: 'critical', source_file: 'builtin',
    cosine_vec: Array.from({ length: VEC_LEN }, (_, i) =>
      -6 + bell(i, 0.04, 0.05, 1.5) - (i / VEC_LEN) * 2
    ),
    kurtosis_score: 5, flatness_score: 0.15, transient_score: 0.1,
  });

  // Piston knock: impulsive, harmonics spilling into 4kHz — log10 baseline ~-5
  referenceIndex.push({
    id: 'builtin-piston', label: 'Piston',
    fault_type: 'piston_knock', severity: 'high', source_file: 'builtin',
    cosine_vec: Array.from({ length: VEC_LEN }, (_, i) => {
      const f = i / VEC_LEN;
      return -5 + bell(i, 0.07, 0.09, 2.5) + 0.4 * Math.abs(Math.sin(f * Math.PI * 5)) * (1 - f);
    }),
    kurtosis_score: 12, flatness_score: 0.12, transient_score: 0.6,
  });

  // Serpentine belt squeal: broadband mid-HF energy — log10 baseline ~-3.5
  referenceIndex.push({
    id: 'builtin-belt', label: 'SerpentineBelt',
    fault_type: 'serpentine_belt', severity: 'medium', source_file: 'builtin',
    cosine_vec: Array.from({ length: VEC_LEN }, (_, i) =>
      -3.5 + bell(i, 0.22, 0.14, 3) + 0.2 * Math.sin((i / VEC_LEN) * Math.PI * 15)
    ),
    kurtosis_score: 4, flatness_score: 0.45, transient_score: 0.2,
  });

  // Power steering whine: tonal mid-band (just above 4kHz) — log10 baseline ~-4
  referenceIndex.push({
    id: 'builtin-powersteer', label: 'PowerSteeringPump',
    fault_type: 'power_steering', severity: 'high', source_file: 'builtin',
    cosine_vec: Array.from({ length: VEC_LEN }, (_, i) => {
      const f = i / VEC_LEN;
      return -4 + bell(i, 0.10, 0.06, 3) + bell(i, 0.22, 0.04, 1.5);
    }),
    kurtosis_score: 8, flatness_score: 0.20, transient_score: 0.15,
  });

  console.log(`[Dataset] ⚠️ Built-in fallback profiles loaded (${referenceIndex.length} entries) — accuracy limited without real fingerprints.`);
}

export async function refreshAudioDataset() {
  await initializeAudioDataset(true);
}
