// Regenerates src/data/yamnet_classes.js from the canonical yamnet_class_map.csv.
// Usage: node scripts/generate_class_map_js.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const csv = fs.readFileSync(path.join(__dirname, 'yamnet_class_map.csv'), 'utf8');
const lines = csv.trim().split('\n').slice(1);
const names = lines.map((raw) => {
  const l = raw.replace(/\r$/, '');
  const m = l.match(/^\d+,[^,]+,(.*)$/);
  if (!m) {
    console.error(`Unparseable line: ${JSON.stringify(l)}`);
    process.exit(1);
  }
  let name = m[1].trim();
  if (name.startsWith('"') && name.endsWith('"')) name = name.slice(1, -1);
  return name;
});
if (names.length !== 521) {
  console.error(`Expected 521 classes, got ${names.length}`);
  process.exit(1);
}
const body =
  '// Canonical YAMNet (AudioSet) class map — 521 classes, index-aligned with the\n' +
  "// model's scores output: index i in this array === column i of the scores tensor.\n" +
  '// Generated by scripts/generate_class_map_js.mjs from scripts/yamnet_class_map.csv.\n' +
  'export const YAMNET_CLASSES = [\n' +
  names.map((n) => `  ${JSON.stringify(n)},`).join('\n') +
  '\n];\n';
fs.writeFileSync(path.join(__dirname, '..', 'src', 'data', 'yamnet_classes.js'), body);
console.log(`written ${names.length} classes`);
console.log('spot checks:', JSON.stringify([names[0], names[132], names[494], names[520]]));
