import fs from 'fs';
import path from 'path';
import * as tf from '@tensorflow/tfjs';

const SUPABASE_URL = 'https://bdldmkhcdtlqxaopxlam.supabase.co';
const YAMNET_MODEL_URL = 'https://tfhub.dev/google/tfjs-model/yamnet/tfjs/1';

const FILES_TO_DOWNLOAD = [
  'alternator_bearing_fault_critical.wav',
  'BearingAlternator.wav',
  'intake_leak_low.wav',
  'misfire_detected_medium.wav',
  'MotorStarter.wav',
  'Piston.wav'
];

function deriveMetadata(baseName) {
  const b = baseName.toLowerCase();
  let fault_type = baseName;
  let severity   = 'high';

  if (b.includes('critical')) severity = 'critical';
  else if (b.includes('medium') || b.includes('moderate')) severity = 'medium';
  else if (b.includes('low'))  severity = 'low';

  if (b.includes('alternator') || (b.includes('bearing') && !b.includes('water')))
    fault_type = 'alternator_bearing_fault';
  else if (b.includes('intake') || b.includes('leak'))
    fault_type = 'intake_leak';
  else if (b.includes('water_pump') || b.includes('waterpump'))
    fault_type = 'water_pump';
  else if (b.includes('motor') || b.includes('starter'))
    fault_type = 'motor_starter';
  else if (b.includes('piston') || b.includes('knock'))
    fault_type = 'piston_knock';
  else if (b.includes('serpentine') || (b.includes('belt') && !b.includes('power')))
    fault_type = 'serpentine_belt';
  else if (b.includes('power_steering') || b.includes('powersteeringpump') || b.includes('powersteer'))
    fault_type = 'power_steering';
  else if (b.includes('timing') || b.includes('chain'))
    fault_type = 'timing_chain';
  else if (b.includes('rocker') || b.includes('valve'))
    fault_type = 'rocker_valve';
  else if (b.includes('low_oil') || b.includes('oil'))
    fault_type = 'low_oil';

  return { 
    label: baseName.replace('.wav', '').replace(/_/g, ' '), 
    fault_type, 
    severity 
  };
}

// Basic 16-bit PCM mono WAV parser
function decodeWav(buffer) {
  // Find the 'data' chunk
  let dataOffset = 12;
  while (dataOffset < buffer.length) {
    const chunkId = buffer.toString('utf8', dataOffset, dataOffset + 4);
    const chunkSize = buffer.readUInt32LE(dataOffset + 4);
    if (chunkId === 'data') {
      dataOffset += 8;
      break;
    }
    dataOffset += 8 + chunkSize;
  }

  const numSamples = Math.floor((buffer.length - dataOffset) / 2);
  const pcm = new Float32Array(numSamples);
  for (let i = 0; i < numSamples; i++) {
    const idx = dataOffset + i * 2;
    if (idx + 1 < buffer.length) {
        const int16 = buffer.readInt16LE(idx);
        pcm[i] = int16 / 32768.0;
    }
  }
  return pcm;
}

async function main() {
  console.log('Loading YAMNet model...');
  const yamnetModel = await tf.loadGraphModel(YAMNET_MODEL_URL, { fromTFHub: true });
  console.log('YAMNet loaded.');

  const fingerprints = [];

  for (const filename of FILES_TO_DOWNLOAD) {
    console.log(`Processing ${filename}...`);
    const url = `${SUPABASE_URL}/storage/v1/object/public/anomaly-patterns/${filename}`;
    
    try {
        const response = await fetch(url);
        if (!response.ok) {
            console.error(`Failed to download ${filename}: ${response.statusText}`);
            continue;
        }
        
        const arrayBuffer = await response.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        
        // Decode WAV
        const pcm = decodeWav(buffer);
        console.log(`Decoded ${pcm.length} samples.`);
        
        if (pcm.length < 16000) {
            console.warn(`File ${filename} is shorter than 1 second. Pading with zeros...`);
        }

        // Run YAMNet
        const embeddingsArray = tf.tidy(() => {
            const waveformTensor = tf.tensor1d(pcm);
            const [scores, embeddings, spectrogram] = yamnetModel.predict(waveformTensor);
            const meanEmbedding = tf.mean(embeddings, 0);
            return Array.from(meanEmbedding.dataSync());
        });
        
        const { label, fault_type, severity } = deriveMetadata(filename);

        fingerprints.push({
            id: filename.replace('.wav', ''),
            label,
            fault_type,
            severity,
            source_file: filename,
            yamnet_embedding: embeddingsArray
        });
        console.log(`Successfully embedded ${filename}`);

    } catch (e) {
        console.error(`Error processing ${filename}:`, e.message);
    }
  }

  const outputJs = `// Auto-generated by scripts/generate_yamnet_embeddings.js
export const YAMNET_FINGERPRINTS = ${JSON.stringify(fingerprints, null, 2)};
`;

  const outPath = path.resolve('./src/data/yamnetFingerprints.js');
  fs.writeFileSync(outPath, outputJs);
  console.log(`\nExported ${fingerprints.length} fingerprints to ${outPath}`);
}

main().catch(console.error);
